### ISSUE TITLE
问下楼主 这里的id是起的什么作用

### ISSUE THREAD

**Issue by watsonnnnn** [1340641314/react-cnode#14]
https://github.com/lzxb/react-cnode/blob/master/src/Component/common/GetNextPage.jsx#L21
问下楼主，这个id是起的啥作用？
这个写一个高阶组件，由它去redux拿state，那只要store里面的state有一点点变了，是不是所有由这个包装过的组件都会相当于触发了一次connect？

**Comment by lzxb** [comment]
不晓得了，这个写得不好。最近有时间可能会重构react-cnode

**Comment by watsonnnnn** [comment]
。。。好的，等楼主出新~

**Comment by lzxb** [comment]
哈哈，最近公司的新项目使用react了。有必要重新熟悉一下react了
