### ISSUE TITLE
请问大大碰到过返回到上一个页面时，页面刷新的问题吗？

### ISSUE THREAD

**Issue by atjiu** [1340641314/react-cnode#15]
List组件点击List里的一条到Detail组件，然后List就被unmount了，再从Detail组件回到List组件，List又重新mount了一遍，然后就会出现List之前翻页到的位置也没有了，直接回到最顶部

想问问这个问题大大碰到过吗？怎么解决的呢？

我用了react-router v4

**Comment by lzxb** [comment]
其实这个问题是状态管理的一种实现，在vue中vuet已经是最佳实践，至于react的话，估计能要等上一两个月了。可能到时候会发布一个react版本的vuet

**Comment by atjiu** [comment]
@lzxb 也就是说，用上redux之后就可以避免这问题了是吧？

**Comment by lzxb** [comment]
这也是其中一种实现的方案

**Comment by atjiu** [comment]
好的，谢谢

**Comment by atjiu** [comment]
@lzxb 发现一个问题，列表往下翻一下，点一个帖子，帖子详情的内容也往下翻了

**Comment by lzxb** [comment]
那就是这里没有做好处理
