### ISSUE TITLE
babel 编译警告

### ISSUE THREAD

**Issue by sunchenguang** [1340641314/react-cnode#5]
`[BABEL] Note: The code generator has deoptimised the styling of "F:/React/react-cnode-master/node_modules/.4.17.2@lodash/lodash.js" as it exceeds the max of "500KB".`

完全按你的README 文件走的，编译会报这个警告。应该是webpack文件没有配置好，麻烦查看。

**Comment by lzxb** [comment]
我没测试，你再试试，修改了 loader: 'babel?presets=es2015&compact=false',

可以参考这里的说明：https://babeljs.io/docs/usage/api/

**Comment by sunchenguang** [comment]
没有警告了
